# Generated by Django 4.2.7 on 2024-01-09 20:37

import SoftLoading.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('D:/Project_Files/Github/WebProjects/RIP/github/media/soft_images'))),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('available', 'available'), ('deleted', 'deleted')], default='available', validators=[SoftLoading.validators.soft_status_validate])),
            ],
            options={
                'db_table': 'Soft',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=10)),
                ('status', models.CharField(blank=True, choices=[('opened', 'opened'), ('paid', 'paid'), ('processed', 'processed'), ('deleted', 'deleted'), ('rejected', 'rejected'), ('completed', 'completed')], default='opened', max_length=30, validators=[SoftLoading.validators.payment_status_validate])),
                ('date_open', models.DateField(auto_now=True)),
                ('date_pay', models.DateField(blank=True, null=True)),
                ('date_close', models.DateField(blank=True, editable=False, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_from_manager_set', to=settings.AUTH_USER_MODEL)),
                ('soft', models.ManyToManyField(to='SoftLoading.soft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Payments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pathlib.PureWindowsPath('D:/Project_Files/Github/WebProjects/RIP/github/media/soft_files'))),
                ('size', models.CharField(blank=True, editable=False, max_length=9)),
                ('platform', models.CharField(blank=True, choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('MacOS', 'MacOS')], max_length=100, null=True, validators=[SoftLoading.validators.file_platform_validate])),
                ('architecture', models.CharField(blank=True, choices=[('x32', 'x32'), ('x64', 'x64')], max_length=3, null=True, validators=[SoftLoading.validators.file_architecture_validate])),
                ('comment', models.TextField(blank=True, null=True)),
                ('soft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoftLoading.soft')),
            ],
            options={
                'db_table': 'Files',
                'managed': True,
            },
        ),
    ]
